# Generated by Django 5.2.10 on 2026-01-31 18:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_unit_options_alter_tenant_id_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitpayment',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.RenameField(
            model_name='unitpayment',
            old_name='payment_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='unitpayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='unitpayment',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='unitpayment',
            name='payer_name',
        ),
        migrations.RemoveField(
            model_name='unitpayment',
            name='status',
        ),
        migrations.AddField(
            model_name='unitpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='unitpayment',
            name='month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='unitpayment',
            name='paid_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='unitpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=30),
        ),
        migrations.AddField(
            model_name='unitpayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unitpayment',
            name='year',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='unitpayment',
            constraint=models.UniqueConstraint(fields=('unit', 'year', 'month'), name='unique_unit_payment_per_month'),
        ),
    ]
