# Generated by Django 5.2.10 on 2026-01-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_unitpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unitpayment',
            name='month',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='unitpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=30),
        ),
        migrations.AlterField(
            model_name='unitpayment',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
