# Generated by Django 5.2.10 on 2026-01-31 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_unitpayment_created_at_alter_unitpayment_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitpayment',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='unitpayment',
            name='unique_unit_payment_per_month',
        ),
        migrations.RemoveField(
            model_name='unitpayment',
            name='received_by',
        ),
    ]
