# Generated by Django 5.2.10 on 2026-02-01 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_unitpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitpayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='unitpayment',
            name='paid_for',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
