# Generated by Django 5.2.10 on 2026-02-02 08:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_unitpayment_options_unitpayment_paid_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='unitpayment',
            name='unit',
        ),
        migrations.AlterField(
            model_name='unitpayment',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='unitpayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='unitpayment',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrears', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='properties.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='properties.unit')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='unitpayment',
            name='tenancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.tenancy'),
        ),
        migrations.AddConstraint(
            model_name='tenancy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('unit',), name='one_active_tenancy_per_unit'),
        ),
    ]
