# Generated by Django 5.2.10 on 2026-02-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_unit_notes_remove_unit_tenant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenancy',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Tenancies'},
        ),
    ]
