# Generated by Django 5.2.10 on 2026-02-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_tenancy_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenancy',
            name='tenant',
        ),
        migrations.AddField(
            model_name='tenancy',
            name='tenants',
            field=models.ManyToManyField(related_name='tenancies', to='properties.tenant'),
        ),
    ]
