# Generated by Django 5.2.10 on 2026-02-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_remove_tenancy_tenant_tenancy_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
