# Generated by Django 5.2.10 on 2026-02-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_tenancy_credit_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitpayment',
            name='type',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='PAID', max_length=10),
        ),
    ]
