# Generated by Django 5.2.10 on 2026-02-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_unitpayment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenancy',
            options={'ordering': ['-start_date']},
        ),
        migrations.RenameField(
            model_name='tenancy',
            old_name='arrears',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='tenancy',
            name='credit_balance',
        ),
        migrations.AlterField(
            model_name='unitpayment',
            name='type',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='PAID', max_length=20),
        ),
    ]
