# Generated by Django 5.2.10 on 2026-02-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_tenancy_options_rename_arrears_tenancy_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitpayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='unitpayment',
            name='type',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=20),
        ),
    ]
