# Generated by Django 5.2.11 on 2026-02-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_businessprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessProfile',
        ),
    ]
