# Generated by Django 5.2.11 on 2026-02-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_chargetype_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargetype',
            name='is_recurring',
        ),
        migrations.AddField(
            model_name='charge',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived')], default='pending', max_length=20),
        ),
    ]
