# Generated by Django 5.2.11 on 2026-02-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_remove_chargetype_is_recurring_charge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitpayment',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
