# Generated by Django 5.2.11 on 2026-02-14 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_auto_20260213_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancymember',
            name='tenancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancy_members', to='properties.tenancy'),
        ),
        migrations.AlterField(
            model_name='tenancymember',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancy_members', to='properties.tenant'),
        ),
    ]
