# Generated by Django 5.2.13 on 2026-04-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_alter_tenancymember_tenancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancy',
            name='billing_start_date',
            field=models.DateField(blank=True, help_text='The date from which rent calculation begins. If blank, start_date is used.', null=True),
        ),
    ]
