# Generated by Django 5.2.14 on 2026-07-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_tenancy_billing_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('bedsitter', 'Bedsitter'), ('house', 'House'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=20),
        ),
    ]
