# Generated by Django 5.2.14 on 2026-07-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenancy',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Tenancies'},
        ),
        migrations.AddField(
            model_name='unitpayment',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('deposit', 'Security Deposit')], default='rent', max_length=20),
        ),
    ]
