# Generated by Django 5.2.17 on 2026-09-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_alter_property_location_alter_property_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitpayment',
            name='paid_for',
        ),
    ]
