# Generated by Django 5.2.17 on 2026-09-04 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_charge_deleted_at_charge_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='is_deleted',
        ),
    ]
