# Generated by Django 5.2.17 on 2026-09-06 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_business_businessmembership_delete_businessprofile_and_more'),
        ('properties', '0030_remove_charge_deleted_at_remove_charge_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargetype',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_types', to='accounts.business'),
        ),
        migrations.AddField(
            model_name='property',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.business'),
        ),
    ]
