# Generated by Django 5.2.17 on 2026-09-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_businessprofile'),
        ('properties', '0031_remove_chargetype_landlord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargetype',
            name='landlord',
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('business', 'name')},
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
    ]
