# Generated by Django 5.2.17 on 2026-09-06 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_businessmembership_business'),
        ('properties', '0032_remove_chargetype_landlord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargetype',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_types', to='accounts.business'),
        ),
        migrations.AlterField(
            model_name='property',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.business'),
        ),
    ]
