# Generated by Django 5.2.17 on 2026-09-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_alter_chargetype_business_alter_property_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitpayment',
            name='source',
            field=models.CharField(choices=[('manual', 'Manually Recorded'), ('stk', 'M-Pesa STK Push')], default='manual', max_length=20),
        ),
    ]
