# Generated by Django 5.2.17 on 2026-09-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_unitpayment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='accrual_type',
            field=models.CharField(blank=True, choices=[('rent', 'Rent Accrual'), ('opening_balance', 'Opening Balance')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
