# Generated by Django 5.2.17 on 2026-09-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_charge_accrual_type_charge_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='accrual_type',
            field=models.CharField(blank=True, choices=[('rent', 'Rent Accrual')], max_length=20, null=True),
        ),
    ]
