# Generated by Django 5.2.17 on 2026-09-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0036_alter_charge_accrual_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='charge_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.chargetype'),
        ),
    ]
