# Generated by Django 5.2.17 on 2026-09-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_alter_charge_charge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='voided_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenancymember',
            name='first_month_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
