# Generated by Django 5.2.17 on 2026-09-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0038_charge_voided_at_charge_voided_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenancymember',
            name='first_month_rent',
        ),
        migrations.AddField(
            model_name='tenancy',
            name='first_month_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
