# Generated by Django 5.2.17 on 2026-09-25 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_mpesatransaction_category_mpesatransaction_notes'),
        ('properties', '0039_remove_tenancymember_first_month_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitpayment',
            name='mpesa_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_payments', to='payments.mpesatransaction'),
        ),
    ]
