# Generated by Django 5.2.16 on 2026-08-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_businessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant')], default='landlord', max_length=10),
        ),
    ]
