# Generated by Django 5.2.17 on 2026-09-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_business_businessmembership_delete_businessprofile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessProfile',
        ),
    ]
