# Generated by Django 5.2.17 on 2026-09-06 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_businessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmembership',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.business'),
        ),
    ]
