# Generated by Django 5.2.17 on 2026-09-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_businessinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinvitation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
