# Generated by Django 5.2.17 on 2026-09-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_legacy_authhandoff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessinvitation',
            options={'ordering': ['-created_at']},
        ),
    ]
