import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "./components/navbar/Navbar";
import Footer from "./components/ui/Footer";
import UnitModal from "./components/modals/UnitModal";
import UnitDetailModal from "./components/modals/UnitDetailModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen">
          {/* Navbar handles PublicNavbar or AppSidebar */}
          <Navbar />

          {/* Main content */}
          <main className="flex-1 mt-12 md:mt-0 pb-10">
            {children}
            
          </main>
          
          {/* Modals */}
          <UnitModal /> 
          <UnitDetailModal />
        </div>
      </body>
    </html>
  );
}
