# Generated by Django 5.2.17 on 2026-09-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('deposit', 'Security Deposit')], default='rent', max_length=20),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
