events {}

http {
    include /etc/nginx/mime.types;
    server_tokens off;

    upstream frontend_server { server frontend:3000; }
    upstream backend_server { server backend:8000; }

    # limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/m; # 10 requests per minute


    server {
        listen 80;

        location / {
            proxy_pass http://frontend_server/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location /static/ {
            alias /usr/src/rentwise/static/;
        }

        location ~ ^/(api|admin)/ {
            proxy_pass http://backend_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            # limit_req zone=api_limit burst=20 nodelay;
        }

    }
}