events {}

http {
    include /etc/nginx/mime.types;
    server_tokens off;

    upstream frontend_server {
        server frontend:3000;
    }

    upstream backend_server {
        server backend:8000;
    }

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/m; # 10 requests per minute

    # Catch-all
    server {
        listen 80 default_server;
        server_name _;
        return 444;
    }

    # Public RentWise website
    server {
        listen 80;
        server_name rentwise.localhost;

        location / {
            proxy_pass http://frontend_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

    # Landlord portal
    server {
        listen 80;
        server_name app.rentwise.localhost;

        location / {
            proxy_pass http://frontend_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

    # Tenant portal
    server {
        listen 80;
        server_name tenant.rentwise.localhost;

        location / {
            proxy_pass http://frontend_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

    # Admin portal
    server {
        listen 80;
        server_name admin.rentwise.localhost;

        location / {
            proxy_pass http://frontend_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

    # Django API
    server {
        listen 80;
        server_name api.rentwise.localhost;

        location / {
            proxy_pass http://backend_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # limit_req zone=api_limit burst=10 nodelay; # 10 requests per minute
        }


        location /static/ {
            alias /usr/src/rentwise/static/;
        }
    }
}